// USUARIO
POST http://localhost:3003/user/signup
Content-Type: application/json

{
   "name":"igor",
   "email":"igor@gmail.com",
   "password":"123456"
}
###
# @name login
POST http://localhost:3003/user/login
Content-Type: application/json

{
   "email":"igor@gmail.com",
   "password":"123456"
}



### Order

POST http://localhost:3003/order/create
Authorization: {{login.response.body.token}}
Content-Type: application/json

{
   "userName":"br",
   "deliveryDate":"2022-10-10"

}

###
GET http://localhost:3003/order
Authorization: {{login.response.body.token}}



### LIST
POST http://localhost:3003/list/create/20
Authorization: {{login.response.body.token}}
Content-Type: application/json

###
GET http://localhost:3003/list
Authorization: {{login.response.body.token}}
Content-Type: application/json

###

DELETE  http://localhost:3003/list/18
Authorization: {{login.response.body.token}}
Content-Type: application/json

### CART --------------------------------------------------

# POST http://localhost:3003/cart/create
# Authorization: {{login.response.body.token}}
# Content-Type: application/json

# {
#    "listId":["43169b73-e24f-4af2-a087-a8f60a9f06de"]
# }

# ###
# GET http://localhost:3003/cart
# Authorization: {{login.response.body.token}}


