// USUARIO
POST http://localhost:3003/user/signup
Content-Type: application/json

{
   "name":"caramelo",
   "email":"caramelo@gmail.com",
   "password":"123456"
}
###
# @name login
POST http://localhost:3003/user/login
Content-Type: application/json

{
   "email":"caramelo@gmail.com",
   "password":"123456"
}

###

POST http://localhost:3003/shopping-list/localhost:3003/create
Authorization: {{login.response.body.token}}
Content-Type: application/json

{
   "userName":"teste",
   "deliveryDate":"04/10/2022",
   "shoppingList":[{"id":16,"name":"AZEITE  PORTUGUÊS EXTRA VIRGEM GALLO 500ML","price":20.49,}]

}

