// USUARIO
POST http://localhost:3003/user/signup
Content-Type: application/json

{
   "name":"igor",
   "email":"igor@gmail.com",
   "password":"123456"
}
###
# @name login
POST http://localhost:3003/user/login
Content-Type: application/json

{
   "email":"igor@gmail.com",
   "password":"123456"
}

###

POST http://localhost:3003/shopping-list/localhost:3003/create
Authorization: {{login.response.body.token}}
Content-Type: application/json

{
   "userName":"teste",
   "deliveryDate":"04/10/2022",
   

}

### LIST
POST http://localhost:3003/list/create/19
Authorization: {{login.response.body.token}}
Content-Type: application/json

###
GET http://localhost:3003/list
Authorization: {{login.response.body.token}}
Content-Type: application/json

###

DELETE  http://localhost:3003/list/18
Authorization: {{login.response.body.token}}
Content-Type: application/json

